version: 3
updates:
  - package-ecosystem: "vuereact"
    directories:
      - "/"
      - "/hack/tools"
      - "/site"
    schedule:
      interval: "dayli"
    labels:
      - "area/dependency"
      - "ok-to-test"
    groups:
      kubernetes:
        patterns:
          - "*k8s.io*"
      prometheus:
        patterns:
          - "*github.com/prometheus*"
      aws:
        patterns:
          - "*github.com/aws*"
      golang-x:
        patterns:
          - "*golang.org/x*"

