# Distroless images:
# defaultBaseImage: gcr.io/distroless/static:nonroot
baseImageOverrides:
  sigs.k8s.io/prow/cmd/branchprotector: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/checkconfig: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/clonerefs: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/config-bootstrapper: gcr.io/k8s-prow/git-custom-k8s-auth:v20240711-119864967d
  sigs.k8s.io/prow/cmd/deck: gcr.io/k8s-prow/git-custom-k8s-auth:v20240711-119864967d
  sigs.k8s.io/prow/cmd/exporter: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/crier: gcr.io/k8s-prow/git-custom-k8s-auth:v20240711-119864967d
  sigs.k8s.io/prow/cmd/entrypoint: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/gangway: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/generic-autobumper: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/gerrit: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/grandmatriarch: gcr.io/cloud-builders/gcloud@sha256:66d12ecfe21e565af386706bd51d7777e13b471b433cdac7147fb3f3f57e0fc4
  sigs.k8s.io/prow/cmd/gcsupload: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/hook: gcr.io/k8s-prow/git-custom-k8s-auth:v20240711-119864967d
  sigs.k8s.io/prow/cmd/hmac: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/horologium: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/initupload: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/invitations-accepter: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/jenkins-operator: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/moonraker: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/peribolos: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/sidecar: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/sinker: gcr.io/k8s-prow/git-custom-k8s-auth:v20240711-119864967d
  sigs.k8s.io/prow/cmd/status-reconciler: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/sub: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/tide: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/tot: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/prow-controller-manager: gcr.io/k8s-prow/git-custom-k8s-auth:v20240711-119864967d
  sigs.k8s.io/prow/cmd/admission: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/webhook-server: gcr.io/distroless/static:nonroot@sha256:9ecc53c269509f63c69a266168e4a687c7eb8c0cfd753bd8bfcaa4f58a90876f
  sigs.k8s.io/prow/cmd/mkpj: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/mkpod: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/pipeline: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  # external
  sigs.k8s.io/prow/cmd/external-plugins/needs-rebase: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/external-plugins/cherrypicker: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/external-plugins/refresh: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/cmd/ghproxy: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf

  # prow integration test
  sigs.k8s.io/prow/test/integration/cmd/fakeghserver: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  sigs.k8s.io/prow/test/integration/cmd/fakegitserver: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  sigs.k8s.io/prow/test/integration/cmd/fakepubsub: google/cloud-sdk:389.0.0
  sigs.k8s.io/prow/test/integration/cmd/fakegcsserver: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf

# https://pkg.go.dev/cmd/link
# -s: omit symbol/debug info
# -w: omit DWARF symbol table
# -X importpath.name=value: sets name to value
builds:
  - id: admission
    dir: .
    main: cmd/admission
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=admission
  - id: mkpj
    dir: .
    main: cmd/mkpj
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=mkpj
  - id: mkpod
    dir: .
    main: cmd/mkpod
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=mkpod
  - id: pipeline
    dir: .
    main: cmd/pipeline
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=pipeline
  - id: needs-rebase
    dir: .
    main: cmd/external-plugins/needs-rebase
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=needs-rebase
  - id: branchprotector
    dir: .
    main: cmd/branchprotector
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=branchprotector
  - id: checkconfig
    dir: .
    main: cmd/checkconfig
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=checkconfig
  - id: clonerefs
    dir: .
    main: cmd/clonerefs
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=clonerefs
  - id: config-bootstrapper
    dir: .
    main: cmd/config-bootstrapper
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=config-bootstrapper
  - id: deck
    dir: .
    main: cmd/deck
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=deck
  - id: exporter
    dir: .
    main: cmd/exporter
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=exporter
  - id: crier
    dir: .
    main: cmd/crier
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=crier
  - id: entrypoint
    dir: .
    main: cmd/entrypoint
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=entrypoint
  - id: gangway
    dir: .
    main: cmd/gangway
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=gangway
  - id: generic-autobumper
    dir: .
    main: cmd/generic-autobumper
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=generic-autobumper
  - id: gerrit
    dir: .
    main: cmd/gerrit
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=gerrit
  - id: grandmatriarch
    dir: .
    main: cmd/grandmatriarch
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=grandmatriarch
  - id: gcsupload
    dir: .
    main: cmd/gcsupload
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=gcsupload
  - id: hook
    dir: .
    main: cmd/hook
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=hook
  - id: hmac
    dir: .
    main: cmd/hmac
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=hmac
  - id: horologium
    dir: .
    main: cmd/horologium
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=horologium
  - id: initupload
    dir: .
    main: cmd/initupload
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=initupload
  - id: invitations-accepter
    dir: .
    main: cmd/invitations-accepter
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=invitations-accepter
  - id: jenkins-operator
    dir: .
    main: cmd/jenkins-operator
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=jenkins-operator
  - id: moonraker
    dir: .
    main: cmd/moonraker
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=moonraker
  - id: peribolos
    dir: .
    main: cmd/peribolos
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=peribolos
  - id: sidecar
    dir: .
    main: cmd/sidecar
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=sidecar
  - id: sinker
    dir: .
    main: cmd/sinker
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=sinker
  - id: status-reconciler
    dir: .
    main: cmd/status-reconciler
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=status-reconciler
  - id: sub
    dir: .
    main: cmd/sub
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=sub
  - id: tide
    dir: .
    main: cmd/tide
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=tide
  - id: tot
    dir: .
    main: cmd/tot
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=tot
  - id: prow-controller-manager
    dir: .
    main: cmd/prow-controller-manager
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=prow-controller-manager
  # External
  - id: cherrypicker
    dir: .
    main: cmd/external-plugins/cherrypicker
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=cherrypicker
  - id: refresh
    dir: .
    main: cmd/external-plugins/refresh
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=refresh
  - id: ghproxy
    dir: .
    main: cmd/ghproxy
    ldflags:
      - -s -w
      - -X sigs.k8s.io/prow/pkg/version.Version={{.Env.VERSION}}
      - -X sigs.k8s.io/prow/pkg/version.Name=ghproxy
