[build]
base = "site/"
publish = "public/"
command = "make netlify-build"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF site"

[build.environment]
HUGO_VERSION = "0.147.8"

[context.production.environment]
HUGO_ENV = "production"
HUGO_BASEURL = "https://docs.prow.k8s.io/"

[context.deploy-preview]
command = "make netlify-deploy-preview"

[context.branch-deploy]
command = "make netlify-deploy-preview"
