/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	v1 "sigs.k8s.io/prow/pkg/apis/prowjobs/v1"
	scheme "sigs.k8s.io/prow/pkg/client/clientset/versioned/scheme"
)

// ProwJobsGetter has a method to return a ProwJobInterface.
// A group's client should implement this interface.
type ProwJobsGetter interface {
	ProwJobs(namespace string) ProwJobInterface
}

// ProwJobInterface has methods to work with ProwJob resources.
type ProwJobInterface interface {
	Create(ctx context.Context, prowJob *v1.ProwJob, opts metav1.CreateOptions) (*v1.ProwJob, error)
	Update(ctx context.Context, prowJob *v1.ProwJob, opts metav1.UpdateOptions) (*v1.ProwJob, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, prowJob *v1.ProwJob, opts metav1.UpdateOptions) (*v1.ProwJob, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ProwJob, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ProwJobList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ProwJob, err error)
	ProwJobExpansion
}

// prowJobs implements ProwJobInterface
type prowJobs struct {
	*gentype.ClientWithList[*v1.ProwJob, *v1.ProwJobList]
}

// newProwJobs returns a ProwJobs
func newProwJobs(c *ProwV1Client, namespace string) *prowJobs {
	return &prowJobs{
		gentype.NewClientWithList[*v1.ProwJob, *v1.ProwJobList](
			"prowjobs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.ProwJob { return &v1.ProwJob{} },
			func() *v1.ProwJobList { return &v1.ProwJobList{} }),
	}
}
