// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: gangway.proto

package gangway

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobExecutionStatus is a 1:1 translation of the existing "ProwJobState" type
// in prow/apis/prowjobs/v1/types.go.
type JobExecutionStatus int32

const (
	JobExecutionStatus_JOB_EXECUTION_STATUS_UNSPECIFIED JobExecutionStatus = 0
	JobExecutionStatus_TRIGGERED                        JobExecutionStatus = 1
	JobExecutionStatus_PENDING                          JobExecutionStatus = 2
	JobExecutionStatus_SUCCESS                          JobExecutionStatus = 3
	JobExecutionStatus_FAILURE                          JobExecutionStatus = 4
	JobExecutionStatus_ABORTED                          JobExecutionStatus = 5
	JobExecutionStatus_ERROR                            JobExecutionStatus = 6
)

// Enum value maps for JobExecutionStatus.
var (
	JobExecutionStatus_name = map[int32]string{
		0: "JOB_EXECUTION_STATUS_UNSPECIFIED",
		1: "TRIGGERED",
		2: "PENDING",
		3: "SUCCESS",
		4: "FAILURE",
		5: "ABORTED",
		6: "ERROR",
	}
	JobExecutionStatus_value = map[string]int32{
		"JOB_EXECUTION_STATUS_UNSPECIFIED": 0,
		"TRIGGERED":                        1,
		"PENDING":                          2,
		"SUCCESS":                          3,
		"FAILURE":                          4,
		"ABORTED":                          5,
		"ERROR":                            6,
	}
)

func (x JobExecutionStatus) Enum() *JobExecutionStatus {
	p := new(JobExecutionStatus)
	*p = x
	return p
}

func (x JobExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gangway_proto_enumTypes[0].Descriptor()
}

func (JobExecutionStatus) Type() protoreflect.EnumType {
	return &file_gangway_proto_enumTypes[0]
}

func (x JobExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobExecutionStatus.Descriptor instead.
func (JobExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_gangway_proto_rawDescGZIP(), []int{0}
}

// JobExecutionType is a 1:1 translation of the existing "ProwJobType" type
// in prow/apis/prowjobs/v1/types.go.
type JobExecutionType int32

const (
	JobExecutionType_JOB_EXECUTION_TYPE_UNSPECIFIED JobExecutionType = 0
	JobExecutionType_PERIODIC                       JobExecutionType = 1
	JobExecutionType_POSTSUBMIT                     JobExecutionType = 2
	JobExecutionType_PRESUBMIT                      JobExecutionType = 3
	JobExecutionType_BATCH                          JobExecutionType = 4
)

// Enum value maps for JobExecutionType.
var (
	JobExecutionType_name = map[int32]string{
		0: "JOB_EXECUTION_TYPE_UNSPECIFIED",
		1: "PERIODIC",
		2: "POSTSUBMIT",
		3: "PRESUBMIT",
		4: "BATCH",
	}
	JobExecutionType_value = map[string]int32{
		"JOB_EXECUTION_TYPE_UNSPECIFIED": 0,
		"PERIODIC":                       1,
		"POSTSUBMIT":                     2,
		"PRESUBMIT":                      3,
		"BATCH":                          4,
	}
)

func (x JobExecutionType) Enum() *JobExecutionType {
	p := new(JobExecutionType)
	*p = x
	return p
}

func (x JobExecutionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobExecutionType) Descriptor() protoreflect.EnumDescriptor {
	return file_gangway_proto_enumTypes[1].Descriptor()
}

func (JobExecutionType) Type() protoreflect.EnumType {
	return &file_gangway_proto_enumTypes[1]
}

func (x JobExecutionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobExecutionType.Descriptor instead.
func (JobExecutionType) EnumDescriptor() ([]byte, []int) {
	return file_gangway_proto_rawDescGZIP(), []int{1}
}

type CreateJobExecutionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobName          string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobExecutionType JobExecutionType       `protobuf:"varint,2,opt,name=job_execution_type,json=jobExecutionType,proto3,enum=JobExecutionType" json:"job_execution_type,omitempty"`
	Refs             *Refs                  `protobuf:"bytes,3,opt,name=refs,proto3" json:"refs,omitempty"`
	PodSpecOptions   *PodSpecOptions        `protobuf:"bytes,4,opt,name=pod_spec_options,json=podSpecOptions,proto3" json:"pod_spec_options,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateJobExecutionRequest) Reset() {
	*x = CreateJobExecutionRequest{}
	mi := &file_gangway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobExecutionRequest) ProtoMessage() {}

func (x *CreateJobExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gangway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobExecutionRequest.ProtoReflect.Descriptor instead.
func (*CreateJobExecutionRequest) Descriptor() ([]byte, []int) {
	return file_gangway_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJobExecutionRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *CreateJobExecutionRequest) GetJobExecutionType() JobExecutionType {
	if x != nil {
		return x.JobExecutionType
	}
	return JobExecutionType_JOB_EXECUTION_TYPE_UNSPECIFIED
}

func (x *CreateJobExecutionRequest) GetRefs() *Refs {
	if x != nil {
		return x.Refs
	}
	return nil
}

func (x *CreateJobExecutionRequest) GetPodSpecOptions() *PodSpecOptions {
	if x != nil {
		return x.PodSpecOptions
	}
	return nil
}

type PodSpecOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envs          map[string]string      `protobuf:"bytes,1,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodSpecOptions) Reset() {
	*x = PodSpecOptions{}
	mi := &file_gangway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodSpecOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodSpecOptions) ProtoMessage() {}

func (x *PodSpecOptions) ProtoReflect() protoreflect.Message {
	mi := &file_gangway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodSpecOptions.ProtoReflect.Descriptor instead.
func (*PodSpecOptions) Descriptor() ([]byte, []int) {
	return file_gangway_proto_rawDescGZIP(), []int{1}
}

func (x *PodSpecOptions) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *PodSpecOptions) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PodSpecOptions) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// Look up a single Prow Job execution.
type GetJobExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobExecutionRequest) Reset() {
	*x = GetJobExecutionRequest{}
	mi := &file_gangway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobExecutionRequest) ProtoMessage() {}

func (x *GetJobExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gangway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetJobExecutionRequest) Descriptor() ([]byte, []int) {
	return file_gangway_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobExecutionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Look up all Prow Job executions that match all fields given here.
type ListJobExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobName       string                 `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`         // Mapped to URL query parameter `job_name`.
	Status        JobExecutionStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=JobExecutionStatus" json:"status,omitempty"` // Mapped to URL query parameter `status`.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobExecutionsRequest) Reset() {
	*x = ListJobExecutionsRequest{}
	mi := &file_gangway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobExecutionsRequest) ProtoMessage() {}

func (x *ListJobExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gangway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListJobExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_gangway_proto_rawDescGZIP(), []int{3}
}

func (x *ListJobExecutionsRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *ListJobExecutionsRequest) GetStatus() JobExecutionStatus {
	if x != nil {
		return x.Status
	}
	return JobExecutionStatus_JOB_EXECUTION_STATUS_UNSPECIFIED
}

type JobExecutions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobExecution  []*JobExecution        `protobuf:"bytes,1,rep,name=job_execution,json=jobExecution,proto3" json:"job_execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobExecutions) Reset() {
	*x = JobExecutions{}
	mi := &file_gangway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobExecutions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobExecutions) ProtoMessage() {}

func (x *JobExecutions) ProtoReflect() protoreflect.Message {
	mi := &file_gangway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobExecutions.ProtoReflect.Descriptor instead.
func (*JobExecutions) Descriptor() ([]byte, []int) {
	return file_gangway_proto_rawDescGZIP(), []int{4}
}

func (x *JobExecutions) GetJobExecution() []*JobExecution {
	if x != nil {
		return x.JobExecution
	}
	return nil
}

type JobExecution struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobName        string                 `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobType        JobExecutionType       `protobuf:"varint,3,opt,name=job_type,json=jobType,proto3,enum=JobExecutionType" json:"job_type,omitempty"`
	JobStatus      JobExecutionStatus     `protobuf:"varint,4,opt,name=job_status,json=jobStatus,proto3,enum=JobExecutionStatus" json:"job_status,omitempty"`
	Refs           *Refs                  `protobuf:"bytes,5,opt,name=refs,proto3" json:"refs,omitempty"`
	PodSpecOptions *PodSpecOptions        `protobuf:"bytes,6,opt,name=pod_spec_options,json=podSpecOptions,proto3" json:"pod_spec_options,omitempty"`
	GcsPath        string                 `protobuf:"bytes,7,opt,name=gcs_path,json=gcsPath,proto3" json:"gcs_path,omitempty"`
	CreateTime     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	CompletionTime *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completion_time,json=completionTime,proto3" json:"completion_time,omitempty"`
	JobUrl         string                 `protobuf:"bytes,10,opt,name=job_url,json=jobUrl,proto3" json:"job_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobExecution) Reset() {
	*x = JobExecution{}
	mi := &file_gangway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobExecution) ProtoMessage() {}

func (x *JobExecution) ProtoReflect() protoreflect.Message {
	mi := &file_gangway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobExecution.ProtoReflect.Descriptor instead.
func (*JobExecution) Descriptor() ([]byte, []int) {
	return file_gangway_proto_rawDescGZIP(), []int{5}
}

func (x *JobExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobExecution) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *JobExecution) GetJobType() JobExecutionType {
	if x != nil {
		return x.JobType
	}
	return JobExecutionType_JOB_EXECUTION_TYPE_UNSPECIFIED
}

func (x *JobExecution) GetJobStatus() JobExecutionStatus {
	if x != nil {
		return x.JobStatus
	}
	return JobExecutionStatus_JOB_EXECUTION_STATUS_UNSPECIFIED
}

func (x *JobExecution) GetRefs() *Refs {
	if x != nil {
		return x.Refs
	}
	return nil
}

func (x *JobExecution) GetPodSpecOptions() *PodSpecOptions {
	if x != nil {
		return x.PodSpecOptions
	}
	return nil
}

func (x *JobExecution) GetGcsPath() string {
	if x != nil {
		return x.GcsPath
	}
	return ""
}

func (x *JobExecution) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *JobExecution) GetCompletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionTime
	}
	return nil
}

func (x *JobExecution) GetJobUrl() string {
	if x != nil {
		return x.JobUrl
	}
	return ""
}

// Refs is a direct, 1:1 translation of the existing "Refs" struct defined in
// prow/apis/prowjobs/v1/types.go.
type Refs struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Org            string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Repo           string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	RepoLink       string                 `protobuf:"bytes,3,opt,name=repo_link,json=repoLink,proto3" json:"repo_link,omitempty"`
	BaseRef        string                 `protobuf:"bytes,4,opt,name=base_ref,json=baseRef,proto3" json:"base_ref,omitempty"`
	BaseSha        string                 `protobuf:"bytes,5,opt,name=base_sha,json=baseSha,proto3" json:"base_sha,omitempty"`
	BaseLink       string                 `protobuf:"bytes,6,opt,name=base_link,json=baseLink,proto3" json:"base_link,omitempty"`
	Pulls          []*Pull                `protobuf:"bytes,7,rep,name=pulls,proto3" json:"pulls,omitempty"`
	PathAlias      string                 `protobuf:"bytes,8,opt,name=path_alias,json=pathAlias,proto3" json:"path_alias,omitempty"`
	WorkDir        bool                   `protobuf:"varint,9,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	CloneUri       string                 `protobuf:"bytes,10,opt,name=clone_uri,json=cloneUri,proto3" json:"clone_uri,omitempty"`
	SkipSubmodules bool                   `protobuf:"varint,11,opt,name=skip_submodules,json=skipSubmodules,proto3" json:"skip_submodules,omitempty"`
	CloneDepth     int32                  `protobuf:"varint,12,opt,name=clone_depth,json=cloneDepth,proto3" json:"clone_depth,omitempty"`
	SkipFetchHead  bool                   `protobuf:"varint,13,opt,name=skip_fetch_head,json=skipFetchHead,proto3" json:"skip_fetch_head,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Refs) Reset() {
	*x = Refs{}
	mi := &file_gangway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refs) ProtoMessage() {}

func (x *Refs) ProtoReflect() protoreflect.Message {
	mi := &file_gangway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refs.ProtoReflect.Descriptor instead.
func (*Refs) Descriptor() ([]byte, []int) {
	return file_gangway_proto_rawDescGZIP(), []int{6}
}

func (x *Refs) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *Refs) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Refs) GetRepoLink() string {
	if x != nil {
		return x.RepoLink
	}
	return ""
}

func (x *Refs) GetBaseRef() string {
	if x != nil {
		return x.BaseRef
	}
	return ""
}

func (x *Refs) GetBaseSha() string {
	if x != nil {
		return x.BaseSha
	}
	return ""
}

func (x *Refs) GetBaseLink() string {
	if x != nil {
		return x.BaseLink
	}
	return ""
}

func (x *Refs) GetPulls() []*Pull {
	if x != nil {
		return x.Pulls
	}
	return nil
}

func (x *Refs) GetPathAlias() string {
	if x != nil {
		return x.PathAlias
	}
	return ""
}

func (x *Refs) GetWorkDir() bool {
	if x != nil {
		return x.WorkDir
	}
	return false
}

func (x *Refs) GetCloneUri() string {
	if x != nil {
		return x.CloneUri
	}
	return ""
}

func (x *Refs) GetSkipSubmodules() bool {
	if x != nil {
		return x.SkipSubmodules
	}
	return false
}

func (x *Refs) GetCloneDepth() int32 {
	if x != nil {
		return x.CloneDepth
	}
	return 0
}

func (x *Refs) GetSkipFetchHead() bool {
	if x != nil {
		return x.SkipFetchHead
	}
	return false
}

// Pull is a direct, 1:1 translation of the existing "Pull" struct defined in
// prow/apis/prowjobs/v1/types.go.
type Pull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Sha           string                 `protobuf:"bytes,3,opt,name=sha,proto3" json:"sha,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Ref           string                 `protobuf:"bytes,5,opt,name=ref,proto3" json:"ref,omitempty"`
	Link          string                 `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
	CommitLink    string                 `protobuf:"bytes,7,opt,name=commit_link,json=commitLink,proto3" json:"commit_link,omitempty"`
	AuthorLink    string                 `protobuf:"bytes,8,opt,name=author_link,json=authorLink,proto3" json:"author_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pull) Reset() {
	*x = Pull{}
	mi := &file_gangway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pull) ProtoMessage() {}

func (x *Pull) ProtoReflect() protoreflect.Message {
	mi := &file_gangway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pull.ProtoReflect.Descriptor instead.
func (*Pull) Descriptor() ([]byte, []int) {
	return file_gangway_proto_rawDescGZIP(), []int{7}
}

func (x *Pull) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Pull) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Pull) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *Pull) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Pull) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *Pull) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Pull) GetCommitLink() string {
	if x != nil {
		return x.CommitLink
	}
	return ""
}

func (x *Pull) GetAuthorLink() string {
	if x != nil {
		return x.AuthorLink
	}
	return ""
}

type BulkJobStatusChangeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobStatusChange *JobStatusChange       `protobuf:"bytes,1,opt,name=job_status_change,json=jobStatusChange,proto3" json:"job_status_change,omitempty"`
	Cluster         string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	StartedBefore   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_before,json=startedBefore,proto3" json:"started_before,omitempty"`
	StartedAfter    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_after,json=startedAfter,proto3" json:"started_after,omitempty"`
	JobType         JobExecutionType       `protobuf:"varint,5,opt,name=job_type,json=jobType,proto3,enum=JobExecutionType" json:"job_type,omitempty"`
	Refs            *Refs                  `protobuf:"bytes,6,opt,name=refs,proto3" json:"refs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BulkJobStatusChangeRequest) Reset() {
	*x = BulkJobStatusChangeRequest{}
	mi := &file_gangway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkJobStatusChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkJobStatusChangeRequest) ProtoMessage() {}

func (x *BulkJobStatusChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gangway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkJobStatusChangeRequest.ProtoReflect.Descriptor instead.
func (*BulkJobStatusChangeRequest) Descriptor() ([]byte, []int) {
	return file_gangway_proto_rawDescGZIP(), []int{8}
}

func (x *BulkJobStatusChangeRequest) GetJobStatusChange() *JobStatusChange {
	if x != nil {
		return x.JobStatusChange
	}
	return nil
}

func (x *BulkJobStatusChangeRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *BulkJobStatusChangeRequest) GetStartedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedBefore
	}
	return nil
}

func (x *BulkJobStatusChangeRequest) GetStartedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAfter
	}
	return nil
}

func (x *BulkJobStatusChangeRequest) GetJobType() JobExecutionType {
	if x != nil {
		return x.JobType
	}
	return JobExecutionType_JOB_EXECUTION_TYPE_UNSPECIFIED
}

func (x *BulkJobStatusChangeRequest) GetRefs() *Refs {
	if x != nil {
		return x.Refs
	}
	return nil
}

type JobStatusChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       JobExecutionStatus     `protobuf:"varint,1,opt,name=current,proto3,enum=JobExecutionStatus" json:"current,omitempty"`
	Desired       JobExecutionStatus     `protobuf:"varint,2,opt,name=desired,proto3,enum=JobExecutionStatus" json:"desired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusChange) Reset() {
	*x = JobStatusChange{}
	mi := &file_gangway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusChange) ProtoMessage() {}

func (x *JobStatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_gangway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusChange.ProtoReflect.Descriptor instead.
func (*JobStatusChange) Descriptor() ([]byte, []int) {
	return file_gangway_proto_rawDescGZIP(), []int{9}
}

func (x *JobStatusChange) GetCurrent() JobExecutionStatus {
	if x != nil {
		return x.Current
	}
	return JobExecutionStatus_JOB_EXECUTION_STATUS_UNSPECIFIED
}

func (x *JobStatusChange) GetDesired() JobExecutionStatus {
	if x != nil {
		return x.Desired
	}
	return JobExecutionStatus_JOB_EXECUTION_STATUS_UNSPECIFIED
}

var File_gangway_proto protoreflect.FileDescriptor

const file_gangway_proto_rawDesc = "" +
	"\n" +
	"\rgangway.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xcd\x01\n" +
	"\x19CreateJobExecutionRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\x12?\n" +
	"\x12job_execution_type\x18\x02 \x01(\x0e2\x11.JobExecutionTypeR\x10jobExecutionType\x12\x19\n" +
	"\x04refs\x18\x03 \x01(\v2\x05.RefsR\x04refs\x129\n" +
	"\x10pod_spec_options\x18\x04 \x01(\v2\x0f.PodSpecOptionsR\x0epodSpecOptions\"\xec\x02\n" +
	"\x0ePodSpecOptions\x12-\n" +
	"\x04envs\x18\x01 \x03(\v2\x19.PodSpecOptions.EnvsEntryR\x04envs\x123\n" +
	"\x06labels\x18\x02 \x03(\v2\x1b.PodSpecOptions.LabelsEntryR\x06labels\x12B\n" +
	"\vannotations\x18\x03 \x03(\v2 .PodSpecOptions.AnnotationsEntryR\vannotations\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"(\n" +
	"\x16GetJobExecutionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"b\n" +
	"\x18ListJobExecutionsRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.JobExecutionStatusR\x06status\"C\n" +
	"\rJobExecutions\x122\n" +
	"\rjob_execution\x18\x01 \x03(\v2\r.JobExecutionR\fjobExecution\"\xa7\x03\n" +
	"\fJobExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bjob_name\x18\x02 \x01(\tR\ajobName\x12,\n" +
	"\bjob_type\x18\x03 \x01(\x0e2\x11.JobExecutionTypeR\ajobType\x122\n" +
	"\n" +
	"job_status\x18\x04 \x01(\x0e2\x13.JobExecutionStatusR\tjobStatus\x12\x19\n" +
	"\x04refs\x18\x05 \x01(\v2\x05.RefsR\x04refs\x129\n" +
	"\x10pod_spec_options\x18\x06 \x01(\v2\x0f.PodSpecOptionsR\x0epodSpecOptions\x12\x19\n" +
	"\bgcs_path\x18\a \x01(\tR\agcsPath\x12;\n" +
	"\vcreate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12C\n" +
	"\x0fcompletion_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionTime\x12\x17\n" +
	"\ajob_url\x18\n" +
	" \x01(\tR\x06jobUrl\"\x82\x03\n" +
	"\x04Refs\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x1b\n" +
	"\trepo_link\x18\x03 \x01(\tR\brepoLink\x12\x19\n" +
	"\bbase_ref\x18\x04 \x01(\tR\abaseRef\x12\x19\n" +
	"\bbase_sha\x18\x05 \x01(\tR\abaseSha\x12\x1b\n" +
	"\tbase_link\x18\x06 \x01(\tR\bbaseLink\x12\x1b\n" +
	"\x05pulls\x18\a \x03(\v2\x05.PullR\x05pulls\x12\x1d\n" +
	"\n" +
	"path_alias\x18\b \x01(\tR\tpathAlias\x12\x19\n" +
	"\bwork_dir\x18\t \x01(\bR\aworkDir\x12\x1b\n" +
	"\tclone_uri\x18\n" +
	" \x01(\tR\bcloneUri\x12'\n" +
	"\x0fskip_submodules\x18\v \x01(\bR\x0eskipSubmodules\x12\x1f\n" +
	"\vclone_depth\x18\f \x01(\x05R\n" +
	"cloneDepth\x12&\n" +
	"\x0fskip_fetch_head\x18\r \x01(\bR\rskipFetchHead\"\xc6\x01\n" +
	"\x04Pull\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x10\n" +
	"\x03sha\x18\x03 \x01(\tR\x03sha\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x10\n" +
	"\x03ref\x18\x05 \x01(\tR\x03ref\x12\x12\n" +
	"\x04link\x18\x06 \x01(\tR\x04link\x12\x1f\n" +
	"\vcommit_link\x18\a \x01(\tR\n" +
	"commitLink\x12\x1f\n" +
	"\vauthor_link\x18\b \x01(\tR\n" +
	"authorLink\"\xc1\x02\n" +
	"\x1aBulkJobStatusChangeRequest\x12<\n" +
	"\x11job_status_change\x18\x01 \x01(\v2\x10.JobStatusChangeR\x0fjobStatusChange\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12A\n" +
	"\x0estarted_before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rstartedBefore\x12?\n" +
	"\rstarted_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fstartedAfter\x12,\n" +
	"\bjob_type\x18\x05 \x01(\x0e2\x11.JobExecutionTypeR\ajobType\x12\x19\n" +
	"\x04refs\x18\x06 \x01(\v2\x05.RefsR\x04refs\"o\n" +
	"\x0fJobStatusChange\x12-\n" +
	"\acurrent\x18\x01 \x01(\x0e2\x13.JobExecutionStatusR\acurrent\x12-\n" +
	"\adesired\x18\x02 \x01(\x0e2\x13.JobExecutionStatusR\adesired*\x88\x01\n" +
	"\x12JobExecutionStatus\x12$\n" +
	" JOB_EXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTRIGGERED\x10\x01\x12\v\n" +
	"\aPENDING\x10\x02\x12\v\n" +
	"\aSUCCESS\x10\x03\x12\v\n" +
	"\aFAILURE\x10\x04\x12\v\n" +
	"\aABORTED\x10\x05\x12\t\n" +
	"\x05ERROR\x10\x06*n\n" +
	"\x10JobExecutionType\x12\"\n" +
	"\x1eJOB_EXECUTION_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bPERIODIC\x10\x01\x12\x0e\n" +
	"\n" +
	"POSTSUBMIT\x10\x02\x12\r\n" +
	"\tPRESUBMIT\x10\x03\x12\t\n" +
	"\x05BATCH\x10\x042\x95\x03\n" +
	"\x04Prow\x12b\n" +
	"\x12CreateJobExecution\x12\x1a.CreateJobExecutionRequest\x1a\r.JobExecution\"!\x82\xd3\xe4\x93\x02\x1b:\x01*B\x16\n" +
	"\x04POST\x12\x0e/v1/executions\x12V\n" +
	"\x0fGetJobExecution\x12\x17.GetJobExecutionRequest\x1a\r.JobExecution\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/executions/{id}\x12V\n" +
	"\x11ListJobExecutions\x12\x19.ListJobExecutionsRequest\x1a\x0e.JobExecutions\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/executions\x12y\n" +
	"\x13BulkJobStatusChange\x12\x1b.BulkJobStatusChangeRequest\x1a\x16.google.protobuf.Empty\"-\x82\xd3\xe4\x93\x02':\x01*B\"\n" +
	"\x04POST\x12\x1a/v1/bulk-job-status-updateB\x1eZ\x1csigs.k8s.io/prow/pkg/gangwayb\x06proto3"

var (
	file_gangway_proto_rawDescOnce sync.Once
	file_gangway_proto_rawDescData []byte
)

func file_gangway_proto_rawDescGZIP() []byte {
	file_gangway_proto_rawDescOnce.Do(func() {
		file_gangway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gangway_proto_rawDesc), len(file_gangway_proto_rawDesc)))
	})
	return file_gangway_proto_rawDescData
}

var file_gangway_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gangway_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_gangway_proto_goTypes = []any{
	(JobExecutionStatus)(0),            // 0: JobExecutionStatus
	(JobExecutionType)(0),              // 1: JobExecutionType
	(*CreateJobExecutionRequest)(nil),  // 2: CreateJobExecutionRequest
	(*PodSpecOptions)(nil),             // 3: PodSpecOptions
	(*GetJobExecutionRequest)(nil),     // 4: GetJobExecutionRequest
	(*ListJobExecutionsRequest)(nil),   // 5: ListJobExecutionsRequest
	(*JobExecutions)(nil),              // 6: JobExecutions
	(*JobExecution)(nil),               // 7: JobExecution
	(*Refs)(nil),                       // 8: Refs
	(*Pull)(nil),                       // 9: Pull
	(*BulkJobStatusChangeRequest)(nil), // 10: BulkJobStatusChangeRequest
	(*JobStatusChange)(nil),            // 11: JobStatusChange
	nil,                                // 12: PodSpecOptions.EnvsEntry
	nil,                                // 13: PodSpecOptions.LabelsEntry
	nil,                                // 14: PodSpecOptions.AnnotationsEntry
	(*timestamppb.Timestamp)(nil),      // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 16: google.protobuf.Empty
}
var file_gangway_proto_depIdxs = []int32{
	1,  // 0: CreateJobExecutionRequest.job_execution_type:type_name -> JobExecutionType
	8,  // 1: CreateJobExecutionRequest.refs:type_name -> Refs
	3,  // 2: CreateJobExecutionRequest.pod_spec_options:type_name -> PodSpecOptions
	12, // 3: PodSpecOptions.envs:type_name -> PodSpecOptions.EnvsEntry
	13, // 4: PodSpecOptions.labels:type_name -> PodSpecOptions.LabelsEntry
	14, // 5: PodSpecOptions.annotations:type_name -> PodSpecOptions.AnnotationsEntry
	0,  // 6: ListJobExecutionsRequest.status:type_name -> JobExecutionStatus
	7,  // 7: JobExecutions.job_execution:type_name -> JobExecution
	1,  // 8: JobExecution.job_type:type_name -> JobExecutionType
	0,  // 9: JobExecution.job_status:type_name -> JobExecutionStatus
	8,  // 10: JobExecution.refs:type_name -> Refs
	3,  // 11: JobExecution.pod_spec_options:type_name -> PodSpecOptions
	15, // 12: JobExecution.create_time:type_name -> google.protobuf.Timestamp
	15, // 13: JobExecution.completion_time:type_name -> google.protobuf.Timestamp
	9,  // 14: Refs.pulls:type_name -> Pull
	11, // 15: BulkJobStatusChangeRequest.job_status_change:type_name -> JobStatusChange
	15, // 16: BulkJobStatusChangeRequest.started_before:type_name -> google.protobuf.Timestamp
	15, // 17: BulkJobStatusChangeRequest.started_after:type_name -> google.protobuf.Timestamp
	1,  // 18: BulkJobStatusChangeRequest.job_type:type_name -> JobExecutionType
	8,  // 19: BulkJobStatusChangeRequest.refs:type_name -> Refs
	0,  // 20: JobStatusChange.current:type_name -> JobExecutionStatus
	0,  // 21: JobStatusChange.desired:type_name -> JobExecutionStatus
	2,  // 22: Prow.CreateJobExecution:input_type -> CreateJobExecutionRequest
	4,  // 23: Prow.GetJobExecution:input_type -> GetJobExecutionRequest
	5,  // 24: Prow.ListJobExecutions:input_type -> ListJobExecutionsRequest
	10, // 25: Prow.BulkJobStatusChange:input_type -> BulkJobStatusChangeRequest
	7,  // 26: Prow.CreateJobExecution:output_type -> JobExecution
	7,  // 27: Prow.GetJobExecution:output_type -> JobExecution
	6,  // 28: Prow.ListJobExecutions:output_type -> JobExecutions
	16, // 29: Prow.BulkJobStatusChange:output_type -> google.protobuf.Empty
	26, // [26:30] is the sub-list for method output_type
	22, // [22:26] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_gangway_proto_init() }
func file_gangway_proto_init() {
	if File_gangway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gangway_proto_rawDesc), len(file_gangway_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gangway_proto_goTypes,
		DependencyIndexes: file_gangway_proto_depIdxs,
		EnumInfos:         file_gangway_proto_enumTypes,
		MessageInfos:      file_gangway_proto_msgTypes,
	}.Build()
	File_gangway_proto = out.File
	file_gangway_proto_goTypes = nil
	file_gangway_proto_depIdxs = nil
}
