// Code generated by go-bindata. (@generated) DO NOT EDIT.

// Package common generated by go-bindata.// sources:
// static/spyglass-lens.html
package common

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _staticSpyglassLensHtml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x8c\x92\x5f\x8b\xd5\x30\x10\xc5\xdf\xef\xa7\x88\x79\xd5\x26\x15\x05\xe5\xd2\x56\x58\xff\xa0\xb0\xa2\xac\x77\x1f\x7c\xba\x4c\x93\xb9\x6d\xee\xa6\x49\xc9\xcc\x82\xa5\xf4\xbb\x4b\x7a\xeb\x3f\x56\xd0\xa7\xc2\x99\xf3\x9b\x33\xd3\x4c\xf5\xe8\xcd\xa7\xd7\x87\xaf\x9f\xdf\x8a\x9e\x07\xdf\xec\xaa\xfc\x11\x1e\x42\x57\x4b\x0c\x32\x0b\x08\xb6\xd9\x09\x51\x0d\xc8\x20\x4c\x0f\x89\x90\x6b\x79\x7b\x78\x57\xbc\x94\x6b\x81\x1d\x7b\x6c\xbe\x8c\x53\xe7\x81\x48\x5c\x63\xa0\xbd\x98\x67\x75\xc8\xfa\xb2\x54\xfa\x62\xc8\xd6\x16\x08\x45\x9f\xf0\x54\xcb\x79\x56\x57\x40\x78\x7b\x73\xbd\x2c\x52\x30\xa4\x2e\xb7\x3d\x8e\x90\x30\xf0\xa5\xb1\x77\xe1\x4e\x24\xf4\xb5\x24\x9e\x3c\x52\x8f\xc8\x72\xc3\x7b\xe6\x91\xf6\x5a\x1b\x1b\xce\xa4\x8c\x8f\xf7\xf6\xe4\x21\xa1\x32\x71\xd0\x70\x86\x6f\xda\xbb\x96\xf4\x00\x8c\xc9\x81\x2f\x2c\x92\xeb\x42\xe1\x1d\xa3\x7e\xaa\x9e\xa9\xf2\x67\x49\xb9\x60\x5d\x17\x8b\xd1\x85\x3b\x35\xb8\xa0\x0c\xd1\x6f\xf9\x7f\xc6\x9d\x62\x60\x52\x5d\x8c\x9d\x47\x18\x1d\xad\x71\x86\xe8\xd5\x09\x06\xe7\xa7\xfa\x26\xb6\x91\xe3\xfe\x79\x59\x3e\x79\x51\x96\xf2\xc1\xf4\xff\xbd\xd7\x5f\x83\x9c\x89\xe1\x47\xd2\xc7\x6d\xfc\xc7\x1f\x4c\x0c\xf4\xef\xc6\x9a\x18\xd8\x19\x4d\xdb\x3b\x69\x8f\x81\x7e\xed\x4a\x26\xb9\x91\x05\x25\xf3\xd0\x7a\xcc\xd6\x63\x7b\x1f\xac\xc7\xf5\x0f\x9d\x49\x36\x95\xbe\x20\x99\x9e\x67\xf5\x1e\xc1\x2e\xcb\xae\xd2\x97\x7b\xa9\xda\x68\x27\x61\x32\x5d\xcb\x8c\x17\x59\x90\x9b\xf9\x2a\xda\x69\x35\x67\xb1\xc9\xd0\x7a\x7c\xdf\x03\x00\x00\xff\xff\xec\xc3\xd6\x08\x8d\x02\x00\x00")

func staticSpyglassLensHtmlBytes() ([]byte, error) {
	return bindataRead(
		_staticSpyglassLensHtml,
		"static/spyglass-lens.html",
	)
}

func staticSpyglassLensHtml() (*asset, error) {
	bytes, err := staticSpyglassLensHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "static/spyglass-lens.html", size: 653, mode: os.FileMode(420), modTime: time.Unix(1, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"static/spyglass-lens.html": staticSpyglassLensHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"static": {nil, map[string]*bintree{
		"spyglass-lens.html": {staticSpyglassLensHtml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
