/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
	v1 "sigs.k8s.io/prow/pkg/apis/prowjobs/v1"
)

// ProwJobLister helps list ProwJobs.
// All objects returned here must be treated as read-only.
type ProwJobLister interface {
	// List lists all ProwJobs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ProwJob, err error)
	// ProwJobs returns an object that can list and get ProwJobs.
	ProwJobs(namespace string) ProwJobNamespaceLister
	ProwJobListerExpansion
}

// prowJobLister implements the ProwJobLister interface.
type prowJobLister struct {
	listers.ResourceIndexer[*v1.ProwJob]
}

// NewProwJobLister returns a new ProwJobLister.
func NewProwJobLister(indexer cache.Indexer) ProwJobLister {
	return &prowJobLister{listers.New[*v1.ProwJob](indexer, v1.Resource("prowjob"))}
}

// ProwJobs returns an object that can list and get ProwJobs.
func (s *prowJobLister) ProwJobs(namespace string) ProwJobNamespaceLister {
	return prowJobNamespaceLister{listers.NewNamespaced[*v1.ProwJob](s.ResourceIndexer, namespace)}
}

// ProwJobNamespaceLister helps list and get ProwJobs.
// All objects returned here must be treated as read-only.
type ProwJobNamespaceLister interface {
	// List lists all ProwJobs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.ProwJob, err error)
	// Get retrieves the ProwJob from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.ProwJob, error)
	ProwJobNamespaceListerExpansion
}

// prowJobNamespaceLister implements the ProwJobNamespaceLister
// interface.
type prowJobNamespaceLister struct {
	listers.ResourceIndexer[*v1.ProwJob]
}
