/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apispipelinev1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	versioned "sigs.k8s.io/prow/pkg/pipeline/clientset/versioned"
	internalinterfaces "sigs.k8s.io/prow/pkg/pipeline/informers/externalversions/internalinterfaces"
	pipelinev1 "sigs.k8s.io/prow/pkg/pipeline/listers/pipeline/v1"
)

// TaskInformer provides access to a shared informer and lister for
// Tasks. Prefer using the type-safe variant (see [TypedTaskInformer]).
type TaskInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() pipelinev1.TaskLister
}

// TypedTaskInformer provides access to a shared informer and lister for
// Tasks, including the type-safe TypedInformer variant.
// It is a superset of TaskInformer.
type TypedTaskInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() TaskIndexInformer
	Lister() pipelinev1.TaskLister
}

// TaskIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type TaskIndexInformer cache.TypedSharedIndexInformer[*apispipelinev1.Task]

// TaskHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for Task.
type TaskHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apispipelinev1.Task]

// TaskDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for Task.
type TaskDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apispipelinev1.Task]

// TaskFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for Task.
type TaskFilteringHandler = cache.TypedFilteringResourceEventHandler[*apispipelinev1.Task]

// TaskIndexers is a specialization of [cache.TypedIndexers] for Task.
type TaskIndexers = cache.TypedIndexers[*apispipelinev1.Task]

// DeletedTask is a specialization of [cache.DeletedObject] for Task.
type DeletedTask = cache.DeletedObject[*apispipelinev1.Task]

type taskInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTaskInformer constructs a new informer for Task type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedTaskInformer]).
func NewTaskInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewTaskInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedTaskInformer constructs a new informer for Task type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedTaskInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers TaskIndexers) TaskIndexInformer {
	return NewTypedTaskInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredTaskInformer constructs a new informer for Task type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredTaskInformer]).
func NewFilteredTaskInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedTaskInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredTaskInformer constructs a new informer for Task type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredTaskInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers TaskIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) TaskIndexInformer {
	return NewTypedTaskInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewTaskInformerWithOptions constructs a new informer for Task type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedTaskInformerWithOptions]).
func NewTaskInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedTaskInformerWithOptions(client, namespace, options)
}

// NewTypedTaskInformerWithOptions constructs a new informer for Task type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedTaskInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) TaskIndexInformer {
	gvr := schema.GroupVersionResource{Group: "tekton.dev", Version: "v1", Resource: "tasks"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apispipelinev1.Task](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TektonV1().Tasks(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TektonV1().Tasks(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TektonV1().Tasks(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.TektonV1().Tasks(namespace).Watch(ctx, opts)
			},
		}, client),
		&apispipelinev1.Task{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *taskInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedTaskInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *taskInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *taskInformer) TypedInformer() TaskIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apispipelinev1.Task](f.factory.InformerFor(&apispipelinev1.Task{}, f.defaultInformer))
}

func (f *taskInformer) Lister() pipelinev1.TaskLister {
	return pipelinev1.NewTaskLister(f.Informer().GetIndexer())
}

// ToTypedTaskInformer converts an untyped informer into a TypedTaskInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Task. If that is not the case, calling type-safe methods of the returned
// TypedTaskInformer leads to runtime panics. A safer alternative is to pass
// around a TypedTaskInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedTaskInformer(informer TaskInformer) TypedTaskInformer {
	if informer, ok := informer.(TypedTaskInformer); ok {
		return informer
	}
	return &taskTypedInformerAdapter{informer}
}

type taskTypedInformerAdapter struct {
	TaskInformer
}

func (a *taskTypedInformerAdapter) TypedInformer() TaskIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apispipelinev1.Task](a.Informer())
}

// ToTaskIndexInformer converts an untyped informer into a TaskIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Task. If that is not the case, calling type-safe methods of the returned
// TaskIndexInformer leads to runtime panics. A safer alternative is to pass
// around a TaskIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToTaskIndexInformer(informer cache.SharedIndexInformer) TaskIndexInformer {
	if informer, ok := informer.(TaskIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apispipelinev1.Task](informer)
}
