images:
  - dir: prow/cmd/admission
  - dir: prow/cmd/branchprotector
  - dir: prow/cmd/checkconfig
  - dir: prow/cmd/config-bootstrapper
  - dir: prow/cmd/deck
  - dir: prow/cmd/exporter
  - dir: prow/cmd/gerrit
  - dir: prow/cmd/crier
  - dir: prow/cmd/gangway
  - dir: prow/cmd/generic-autobumper
  - dir: prow/cmd/grandmatriarch
  - dir: prow/cmd/gcsupload
  - dir: prow/cmd/hook
  - dir: prow/cmd/hmac
  - dir: prow/cmd/horologium
  - dir: prow/cmd/invitations-accepter
  - dir: prow/cmd/jenkins-operator
  - dir: prow/cmd/mkpj
  - dir: prow/cmd/mkpod
  - dir: prow/cmd/moonraker
  - dir: prow/cmd/peribolos
  - dir: prow/cmd/sinker
  - dir: prow/cmd/status-reconciler
  - dir: prow/cmd/sub
  - dir: prow/cmd/tide
  - dir: prow/cmd/tot
  - dir: prow/cmd/pipeline
  - dir: prow/cmd/prow-controller-manager
  - dir: prow/cmd/webhook-server
  # pod utils
  - dir: prow/cmd/clonerefs
    arch: all
  - dir: prow/cmd/entrypoint
    arch: all
  - dir: prow/cmd/initupload
    arch: all
  - dir: prow/cmd/sidecar
    arch: all
  - dir: prow/external-plugins/needs-rebase
  - dir: prow/external-plugins/cherrypicker
  - dir: prow/external-plugins/refresh
  - dir: ghproxy
